### ISSUE TITLE
Relevant information for ground truth generation

### ISSUE THREAD

**Issue by icarl-ad** [stefanklut/laypa#42]
Hi, 

we are currently rethinking our ground truth generation rules. We have some questions regarding the baselines and text regions:

- Is it essential for a training that the baselines are numbered so that there is a reading order within the text region?
- How is the reading order of the baselines determined within a text region during inference?
- Is the detection of text regions essential for the following steps (HTR etc.) of inference?
- Is it possible to train a segmentation model to have one region per coherent text paragraph so that the reading order of the baselines within the text region is logical?

Thank you in advance!

**Comment by stefanklut** [comment]
Hi there,

The regions and reading order are normally done as a post processing step. The trained region models are specifically for detecting known page structures (e.g. distinction between marginalia and main text is necessary). The trained models use pixel wise classification. So to specifically answer your questions:

- The baseline ordering is done in post processing in the Loghi-tooling ([https://github.com/knaw-huc/loghi-tooling](https://github.com/knaw-huc/loghi-tooling)) step. It is our ambition to also do something with AI models to get the reading order correct, however this is not something we will likely do in the near future
- The main method used in Loghi-tooling is to group text lines based on interline distance. And within these groups, the lines are ordered from top to bottom. The groups themselves are also ordered based on some handcrafted rules.
- The standard method does not use the region model at all. The trained region models are only there as an enhancement if you know your data has certain structures. All inference will work with just a baseline model
- I'm not sure I understand you correctly, but the trained region model does classification on a pixel level. And generally the only classes of paragraphs are too close together to be split by a background class. The region model serves more to distinguish main text from e.g. Signatures, images, or headers. Not make splits in the main text itself. If this is something you require, I suggest having a look at instance based models. These had the downside of being restricted to bounding boxes, which is why we chose the pixel based approach

I hope this clears up all your questions, and if not feel free to ask more
