### ISSUE TITLE
Difference between training region and baseline model

### ISSUE THREAD

**Issue by icarl-ad** [stefanklut/laypa#45]
Hi,

can you please explain to me the difference between the baseline and region models?

The baseline2 model that can be downloaded via https://surfdrive.surf.nl/files/index.php/s/YA8HJuukIUKznSP?path=%2Flaypa%2Fgeneral%2Fbaseline2 returns not just baselines but also text regions.

That got me wondering what the use case for the region training is.

Thanks in advance!

**Comment by stefanklut** [comment]
The text regions generated by loghi using the normal baseline model are not structural tags (e.g. Header, Body, Marginalia). They just group the text into chunks that are close together. The region model tries to predict the both the region area and the region class

Example:
![NL-HaNA_1 01 02_3204_0463_regions](https://github.com/user-attachments/assets/e30a7a33-7ccd-446b-8ba5-3f73f6e3b529)

The simple baseline model would just have rectangles around grouped baselines

**Comment by icarl-ad** [comment]
That makes sense. I trained a region model and tried to test it (I tested it in loghi with a baseline model and a HTR model). I got the following error message:
![image](https://github.com/user-attachments/assets/e22f416c-1045-4c13-b4c0-37dd28713288)
Do you have an idea what I did wrong? Thanks in advance!

**Comment by stefanklut** [comment]
This is due to the fact that you are using the experimental class_baseline mode. This will output a class for each baseline. It takes what class it should be from the class of the region it is in. The output mode to pageXML is not really defined yet, as code to combine the baselines back into regions is not fully developed yet. Did you use the configs/segmentation/region/region_baseline_test.yaml config? I suggest looking at configs/segmentation/region/region_dataset_globalise.yaml or configs/segmentation/region/region_dataset.yaml Although for the final one you have to add the regions in the same way as the globalise config
